site_name: mkdocs test
site_url: http://philippaffolter.github.io/www-mkdocs
repo_name: pa-mkdocs
repo_url: https://github.com/philippaffolter/www-mkdocs
edit_uri: ""

copyright: 'Copyright &copy; 2022 by Testers'

# change directory names here
#docs_dir: doc
site_dir: site

theme:
  name: material

  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'green'
    accent: 'purple'
  
  # fun logos! see https://material.io/icons/
  icon:
    logo: material/dns

  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# give a title for each page
nav:
  - 'Home': 'index.md'
  - 'About': 'about.md'
  - 'Installation':
    - 'Requirements': 'system_requirements.md'
    - 'Bioconda': 'install.md'
